# routes.yml
list_users:
    path:     /users
    defaults: { _controller: 'MiW16\Results\Controller\UserController', _action: 'showAllAction' }

show_user:
    path:     /users/{id_user}
    defaults: { _controller: 'MiW16\Results\Controller\UserController', _action: 'showOneAction', _param: 'id_user' }

add_user:
    path:     /users/add
    defaults: { _controller: 'MiW16\Results\Controller\UserController', _action: 'addUserAction' }

remove_user:
    path:     /users/{id_user}/remove
    defaults: { _controller: 'MiW16\Results\Controller\UserController', _action: 'removeUserAction', _param: 'id_user' }

update_user:
    path:     /users/{id_user}/update
    defaults: { _controller: 'MiW16\Results\Controller\UserController', _action: 'updateUserAction', _param: 'id_user' }

    