<html>
    <head>
        <title>Results - add users</title>
    </head>
    <body>
        <form action="#" id="user_add_form" method="POST">
            <label>Username</label>
            <input type="text" name="username" value="" required>
            <br/>
            <label>Email</label>
            <input type="text" name="email" value="" required>
            <br/>
            <label>Password</label>
            <input type="password" name="password" value="" required>
            <br/>
            <button type="submit">Añadir</button>
        </form>
    </body>
</html>